// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package content

import (
	"context"
	"time"
)

const deleteBlogPostBySlug = `-- name: DeleteBlogPostBySlug :execrows
DELETE FROM blog_posts
WHERE slug = ?
`

func (q *Queries) DeleteBlogPostBySlug(ctx context.Context, slug string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBlogPostBySlug, slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMusicTrackByID = `-- name: DeleteMusicTrackByID :execrows
DELETE FROM music_tracks
WHERE id = ?
`

func (q *Queries) DeleteMusicTrackByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMusicTrackByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProjectByID = `-- name: DeleteProjectByID :execrows
DELETE FROM projects
WHERE id = ?
`

func (q *Queries) DeleteProjectByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProjectByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSocialLinkByID = `-- name: DeleteSocialLinkByID :execrows
DELETE FROM social_links
WHERE id = ?
`

func (q *Queries) DeleteSocialLinkByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSocialLinkByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertBlogPost = `-- name: InsertBlogPost :exec
INSERT INTO blog_posts (
    id, slug, title, excerpt, body, published_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type InsertBlogPostParams struct {
	ID          string    `json:"id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Excerpt     string    `json:"excerpt"`
	Body        string    `json:"body"`
	PublishedAt time.Time `json:"published_at"`
}

func (q *Queries) InsertBlogPost(ctx context.Context, arg InsertBlogPostParams) error {
	_, err := q.db.ExecContext(ctx, insertBlogPost,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Body,
		arg.PublishedAt,
	)
	return err
}

const insertMusicTrack = `-- name: InsertMusicTrack :exec
INSERT INTO music_tracks (
    id, title, genre, flac_url, mp3_url, soundcloud_url, youtube_url, cover_image, release_date
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertMusicTrackParams struct {
	ID            string    `json:"id"`
	Title         string    `json:"title"`
	Genre         string    `json:"genre"`
	FlacUrl       string    `json:"flac_url"`
	Mp3Url        string    `json:"mp3_url"`
	SoundcloudUrl string    `json:"soundcloud_url"`
	YoutubeUrl    string    `json:"youtube_url"`
	CoverImage    string    `json:"cover_image"`
	ReleaseDate   time.Time `json:"release_date"`
}

func (q *Queries) InsertMusicTrack(ctx context.Context, arg InsertMusicTrackParams) error {
	_, err := q.db.ExecContext(ctx, insertMusicTrack,
		arg.ID,
		arg.Title,
		arg.Genre,
		arg.FlacUrl,
		arg.Mp3Url,
		arg.SoundcloudUrl,
		arg.YoutubeUrl,
		arg.CoverImage,
		arg.ReleaseDate,
	)
	return err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO projects (
    id, name, description, repo_url, tech_stack
) VALUES (
    ?, ?, ?, ?, ?
)
`

type InsertProjectParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	RepoUrl     string `json:"repo_url"`
	TechStack   string `json:"tech_stack"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RepoUrl,
		arg.TechStack,
	)
	return err
}

const updateBlogPostBySlug = `-- name: UpdateBlogPostBySlug :execrows
UPDATE blog_posts
SET
    slug = ?,
    title = ?,
    excerpt = ?,
    body = ?,
    published_at = ?
WHERE slug = ?
`

type UpdateBlogPostBySlugParams struct {
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Excerpt     string    `json:"excerpt"`
	Body        string    `json:"body"`
	PublishedAt time.Time `json:"published_at"`
	Slug_2      string    `json:"slug_2"`
}

func (q *Queries) UpdateBlogPostBySlug(ctx context.Context, arg UpdateBlogPostBySlugParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBlogPostBySlug,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Body,
		arg.PublishedAt,
		arg.Slug_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSocialLinkByID = `-- name: UpdateSocialLinkByID :execrows
UPDATE social_links
SET
    name = ?,
    url = ?
WHERE id = ?
`

type UpdateSocialLinkByIDParams struct {
	Name string `json:"name"`
	Url  string `json:"url"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateSocialLinkByID(ctx context.Context, arg UpdateSocialLinkByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSocialLinkByID, arg.Name, arg.Url, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
