// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blog.sql

package content

import (
	"context"
	"time"
)

const createBlogPost = `-- name: CreateBlogPost :exec
INSERT OR IGNORE INTO blog_posts (
    id, slug, title, excerpt, body, published_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type CreateBlogPostParams struct {
	ID          string    `json:"id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Excerpt     string    `json:"excerpt"`
	Body        string    `json:"body"`
	PublishedAt time.Time `json:"published_at"`
}

func (q *Queries) CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) error {
	_, err := q.db.ExecContext(ctx, createBlogPost,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Body,
		arg.PublishedAt,
	)
	return err
}

const getBlogPostBySlug = `-- name: GetBlogPostBySlug :one
SELECT id, slug, title, excerpt, body, published_at
FROM blog_posts
WHERE slug = ?
LIMIT 1
`

func (q *Queries) GetBlogPostBySlug(ctx context.Context, slug string) (BlogPost, error) {
	row := q.db.QueryRowContext(ctx, getBlogPostBySlug, slug)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.PublishedAt,
	)
	return i, err
}

const listBlogPosts = `-- name: ListBlogPosts :many
SELECT id, slug, title, excerpt, body, published_at
FROM blog_posts
ORDER BY published_at DESC, title ASC
`

func (q *Queries) ListBlogPosts(ctx context.Context) ([]BlogPost, error) {
	rows, err := q.db.QueryContext(ctx, listBlogPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPost
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Body,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
