// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package content

import (
	"time"
)

type BlogPost struct {
	ID          string    `json:"id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Excerpt     string    `json:"excerpt"`
	Body        string    `json:"body"`
	PublishedAt time.Time `json:"published_at"`
}

type MusicTrack struct {
	ID            string    `json:"id"`
	Title         string    `json:"title"`
	Genre         string    `json:"genre"`
	FlacUrl       string    `json:"flac_url"`
	Mp3Url        string    `json:"mp3_url"`
	SoundcloudUrl string    `json:"soundcloud_url"`
	YoutubeUrl    string    `json:"youtube_url"`
	CoverImage    string    `json:"cover_image"`
	ReleaseDate   time.Time `json:"release_date"`
}

type Project struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	RepoUrl     string `json:"repo_url"`
	TechStack   string `json:"tech_stack"`
}

type SocialLink struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Url  string `json:"url"`
}
