// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: music.sql

package content

import (
	"context"
	"time"
)

const createMusicTrack = `-- name: CreateMusicTrack :exec
INSERT OR IGNORE INTO music_tracks (
    id, title, genre, flac_url, mp3_url, soundcloud_url, youtube_url, cover_image, release_date
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateMusicTrackParams struct {
	ID            string    `json:"id"`
	Title         string    `json:"title"`
	Genre         string    `json:"genre"`
	FlacUrl       string    `json:"flac_url"`
	Mp3Url        string    `json:"mp3_url"`
	SoundcloudUrl string    `json:"soundcloud_url"`
	YoutubeUrl    string    `json:"youtube_url"`
	CoverImage    string    `json:"cover_image"`
	ReleaseDate   time.Time `json:"release_date"`
}

func (q *Queries) CreateMusicTrack(ctx context.Context, arg CreateMusicTrackParams) error {
	_, err := q.db.ExecContext(ctx, createMusicTrack,
		arg.ID,
		arg.Title,
		arg.Genre,
		arg.FlacUrl,
		arg.Mp3Url,
		arg.SoundcloudUrl,
		arg.YoutubeUrl,
		arg.CoverImage,
		arg.ReleaseDate,
	)
	return err
}

const listMusicTracks = `-- name: ListMusicTracks :many
SELECT id, title, genre, flac_url, mp3_url, soundcloud_url, youtube_url, cover_image, release_date
FROM music_tracks
ORDER BY release_date DESC, title ASC
`

func (q *Queries) ListMusicTracks(ctx context.Context) ([]MusicTrack, error) {
	rows, err := q.db.QueryContext(ctx, listMusicTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MusicTrack
	for rows.Next() {
		var i MusicTrack
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Genre,
			&i.FlacUrl,
			&i.Mp3Url,
			&i.SoundcloudUrl,
			&i.YoutubeUrl,
			&i.CoverImage,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
