// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package content

import (
	"context"
)

const createProject = `-- name: CreateProject :exec
INSERT OR IGNORE INTO projects (
    id, name, description, repo_url, tech_stack
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreateProjectParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	RepoUrl     string `json:"repo_url"`
	TechStack   string `json:"tech_stack"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RepoUrl,
		arg.TechStack,
	)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, repo_url, tech_stack
FROM projects
ORDER BY id ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RepoUrl,
			&i.TechStack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
