// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social_links.sql

package content

import (
	"context"
)

const createSocialLink = `-- name: CreateSocialLink :exec
INSERT OR IGNORE INTO social_links (
    id, name, url
) VALUES (
    ?, ?, ?
)
`

type CreateSocialLinkParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Url  string `json:"url"`
}

func (q *Queries) CreateSocialLink(ctx context.Context, arg CreateSocialLinkParams) error {
	_, err := q.db.ExecContext(ctx, createSocialLink, arg.ID, arg.Name, arg.Url)
	return err
}

const listSocialLinks = `-- name: ListSocialLinks :many
SELECT id, name, url
FROM social_links
ORDER BY id ASC
`

func (q *Queries) ListSocialLinks(ctx context.Context) ([]SocialLink, error) {
	rows, err := q.db.QueryContext(ctx, listSocialLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialLink
	for rows.Next() {
		var i SocialLink
		if err := rows.Scan(&i.ID, &i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
